## Preprocessing

In [2]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

# Import pandas and read the charity_data.csv from the provided cloud URL.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [3]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df = application_df.drop(columns=['EIN', 'NAME'])
application_df.head()

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [4]:
# Determine the number of unique values in each column.
unique_counts= application_df.nunique()
unique_counts

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [5]:
# Look at APPLICATION_TYPE value counts to identify and replace with "Other"
application_type_counts = application_df["APPLICATION_TYPE"].value_counts()
application_type_counts

APPLICATION_TYPE
T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: count, dtype: int64

In [6]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
cutoff_value = 500
application_types_to_replace = application_type_counts[application_type_counts < cutoff_value].index.tolist()

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure replacement was successful
application_df['APPLICATION_TYPE'].value_counts()

APPLICATION_TYPE
T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: count, dtype: int64

In [7]:
# Look at CLASSIFICATION value counts to identify and replace with "Other"
classification_counts = application_df["CLASSIFICATION"].value_counts()
classification_counts

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: count, Length: 71, dtype: int64

In [8]:
# You may find it helpful to look at CLASSIFICATION value counts >1
classification_counts[classification_counts > 1]

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: count, dtype: int64

In [9]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
cutoff_value = 500
classifications_to_replace = classification_counts[classification_counts < cutoff_value].index.tolist()
# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure replacement was successful
application_df['CLASSIFICATION'].value_counts()

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
Other     1484
C7000      777
Name: count, dtype: int64

In [10]:
# Convert categorical data to numeric with `pd.get_dummies`
df_encoded = pd.get_dummies(application_df, dtype=int)
df_encoded.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,1,108590,1,0,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,1,0
2,1,5000,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
3,1,6692,1,0,0,0,1,0,0,0,...,0,1,0,0,0,0,0,0,1,0
4,1,142590,1,0,0,0,1,0,0,0,...,0,0,1,0,0,0,0,0,1,0

In [11]:
# Split our preprocessed data into our features and target arrays
y = df_encoded["IS_SUCCESSFUL"].values
X = df_encoded.drop(columns=["IS_SUCCESSFUL"]).values

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((27439, 44), (6860, 44), (27439,), (6860,))

In [12]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [13]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.


nn = tf.keras.models.Sequential()

input_nodes = X_train_scaled.shape[1]

# First hidden layer
nn.add(tf.keras.layers.Dense(units=80, activation="relu", input_dim=input_nodes))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=30, activation="relu"))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (None, 80)                  │           3,600 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 30)                  │           2,430 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ (None, 1)                   │              31 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 6,061 (23.68 KB)

 Trainable params: 6,061 (23.68 KB)

 Non-trainable params: 0 (0.00 B)

In [14]:
# Compile the model
nn.compile(optimizer="adam",
           loss="binary_crossentropy",
           metrics=["accuracy"])

In [15]:
# Train the model
history = nn.fit(X_train_scaled, y_train, epochs=50, batch_size=32, validation_data=(X_test_scaled, y_test))

Epoch 1/50
858/858 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.6960 - loss: 0.5932 - val_accuracy: 0.7216 - val_loss: 0.5638
Epoch 2/50
858/858 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7325 - loss: 0.5508 - val_accuracy: 0.7181 - val_loss: 0.5632
Epoch 3/50
858/858 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.7326 - loss: 0.5494 - val_accuracy: 0.7254 - val_loss: 0.5598
Epoch 4/50
858/858 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7295 - loss: 0.5495 - val_accuracy: 0.7257 - val_loss: 0.5593
Epoch 5/50
858/858 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - accuracy: 0.7306 - loss: 0.5507 - val_accuracy: 0.7245 - val_loss: 0.5601
Epoch 6/50
858/858 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.7332 - loss: 0.5476 - val_accuracy: 0.7239 - val_loss: 0.5591
Epoch 7/50
858/858 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7302 - loss: 0.5481 - val_accuracy: 0.7283 - val_loss: 0.5551
Epoch 8/50
858/858 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7301 - loss: 0.5472 - val_accuracy: 0.7252 - val_loss: 0.5561
Epoch 9/50
858/858 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7344 - loss: 0.5431 - val_accuracy: 0.7230 - val_loss: 0.5568
Epoch 10/50
858/858 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.7274 - loss: 0.5484 - val_accuracy: 0.7292 - val_loss: 0.5559
Epoch 11/50
858/858 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.7403 - loss: 0.5364 - val_accuracy: 0.7283 - val_loss: 0.5529
Epoch 12/50
858/858 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.7327 - loss: 0.5432 - val_accuracy: 0.7278 - val_loss: 0.5579
Epoch 13/50
858/858 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7388 - loss: 0.5383 - val_accuracy: 0.7302 - val_loss: 0.5543
Epoch 14/50
858/858 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7380 - loss: 0.5379 - val_accuracy: 0.7290 - val_loss: 0.5529
Epoch 15/50
858/858 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7340 - loss: 0.5446 - val_accuracy: 0.7262 - val_loss: 0.5560
Epoch 16/50
858/858 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.7341 - loss: 0.5431 - val_accuracy: 0.7258 - val_loss: 0.5569
Epoch 17/50
858/858 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.7349 - loss: 0.5406 - val_accuracy: 0.7294 - val_loss: 0.5541
Epoch 18/50
858/858 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7348 - loss: 0.5396 - val_accuracy: 0.7286 - val_loss: 0.5544
Epoch 19/50
858/858 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7381 - loss: 0.5394 - val_accuracy: 0.7271 - val_loss: 0.5549
Epoch 20/50
858/858 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7403 - loss: 0.5372 - val_accuracy: 0.7254 - val_loss: 0.5579
Epoch 21/50
858/858 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7370 - loss: 0.5363 - val_accuracy: 0.7277 - val_loss: 0.5539
Epoch 22/50
858/858 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7378 - loss: 0.5380 - val_accuracy: 0.7299 - val_loss: 0.5557
Epoch 23/50
858/858 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7351 - loss: 0.5438 - val_accuracy: 0.7222 - val_loss: 0.5552
Epoch 24/50
858/858 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7398 - loss: 0.5390 - val_accuracy: 0.7261 - val_loss: 0.5567
Epoch 25/50
858/858 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7427 - loss: 0.5322 - val_accuracy: 0.7283 - val_loss: 0.5545
Epoch 26/50
858/858 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7396 - loss: 0.5393 - val_accuracy: 0.7241 - val_loss: 0.5563
Epoch 27/50
858/858 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7371 - loss: 0.5389 - val_accuracy: 0.7290 - val_loss: 0.5568
Epoch 28/50
858/858 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7386 - loss: 0.5360 - val_accuracy: 0.7281 - val_loss: 0.5572
Epoch 29/50
858/858 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.7388 - loss: 0.5369 - val_accuracy: 0.7270 - val_loss: 0.5564
Epoch 30/50
858/858 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7354 - loss: 0.5389 - val_accuracy: 0.7281 - val_loss: 0.5553
Epoch 31/50
858/858 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7421 - loss: 0.5363 - val_accuracy: 0.7230 - val_loss: 0.5588
Epoch 32/50
858/858 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7406 - loss: 0.5353 - val_accuracy: 0.7233 - val_loss: 0.5594
Epoch 33/50
858/858 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.7388 - loss: 0.5350 - val_accuracy: 0.7262 - val_loss: 0.5566
Epoch 34/50
858/858 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7363 - loss: 0.5377 - val_accuracy: 0.7265 - val_loss: 0.5568
Epoch 35/50
858/858 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7407 - loss: 0.5339 - val_accuracy: 0.7261 - val_loss: 0.5565
Epoch 36/50
858/858 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7410 - loss: 0.5319 - val_accuracy: 0.7239 - val_loss: 0.5575
Epoch 37/50
858/858 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.7423 - loss: 0.5320 - val_accuracy: 0.7246 - val_loss: 0.5577
Epoch 38/50
858/858 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7349 - loss: 0.5405 - val_accuracy: 0.7251 - val_loss: 0.5576
Epoch 39/50
858/858 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7395 - loss: 0.5336 - val_accuracy: 0.7258 - val_loss: 0.5552
Epoch 40/50
858/858 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7382 - loss: 0.5368 - val_accuracy: 0.7254 - val_loss: 0.5584
Epoch 41/50
858/858 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.7424 - loss: 0.5350 - val_accuracy: 0.7289 - val_loss: 0.5549
Epoch 42/50
858/858 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7365 - loss: 0.5393 - val_accuracy: 0.7276 - val_loss: 0.5578
Epoch 43/50
858/858 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7412 - loss: 0.5357 - val_accuracy: 0.7283 - val_loss: 0.5551
Epoch 44/50
858/858 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7468 - loss: 0.5276 - val_accuracy: 0.7277 - val_loss: 0.5557
Epoch 45/50
858/858 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.7426 - loss: 0.5333 - val_accuracy: 0.7243 - val_loss: 0.5570
Epoch 46/50
858/858 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7405 - loss: 0.5325 - val_accuracy: 0.7249 - val_loss: 0.5574
Epoch 47/50
858/858 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7371 - loss: 0.5373 - val_accuracy: 0.7276 - val_loss: 0.5560
Epoch 48/50
858/858 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7389 - loss: 0.5338 - val_accuracy: 0.7264 - val_loss: 0.5575
Epoch 49/50
858/858 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7413 - loss: 0.5348 - val_accuracy: 0.7261 - val_loss: 0.5567
Epoch 50/50
858/858 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7370 - loss: 0.5413 - val_accuracy: 0.7286 - val_loss: 0.5582

In [16]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

215/215 - 0s - 2ms/step - accuracy: 0.7286 - loss: 0.5582
Loss: 0.5581749081611633, Accuracy: 0.7285714149475098

In [17]:
# Export our model to HDF5 file
nn.save("charity_model.h5")

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [18]:
# Define an optimized model
optimized_nn = tf.keras.models.Sequential()

# Input layer & first hidden layer (more neurons)
optimized_nn.add(tf.keras.layers.Dense(units=128, activation="relu", input_dim=X_train_scaled.shape[1]))

# Second hidden layer
optimized_nn.add(tf.keras.layers.Dense(units=64, activation="relu"))

# Third hidden layer (newly added)
optimized_nn.add(tf.keras.layers.Dense(units=32, activation="relu"))

# Dropout layer to prevent overfitting
optimized_nn.add(tf.keras.layers.Dropout(0.2))

# Output layer
optimized_nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Compile the model
optimized_nn.compile(optimizer="adam",
                     loss="binary_crossentropy",
                     metrics=["accuracy"])

# Train the optimized model with more epochs
history = optimized_nn.fit(X_train_scaled, y_train, epochs=100, batch_size=32, validation_data=(X_test_scaled, y_test))

# Evaluate performance
model_loss, model_accuracy = optimized_nn.evaluate(X_test_scaled, y_test, verbose=2)
print(f"Optimized Loss: {model_loss}, Optimized Accuracy: {model_accuracy}")

# Save the optimized model
optimized_nn.save("optimized_charity_model.h5")

Epoch 1/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.7066 - loss: 0.5889 - val_accuracy: 0.7249 - val_loss: 0.5613
Epoch 2/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.7265 - loss: 0.5568 - val_accuracy: 0.7262 - val_loss: 0.5564
Epoch 3/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.7336 - loss: 0.5540 - val_accuracy: 0.7305 - val_loss: 0.5568
Epoch 4/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7345 - loss: 0.5486 - val_accuracy: 0.7258 - val_loss: 0.5566
Epoch 5/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.7345 - loss: 0.5491 - val_accuracy: 0.7223 - val_loss: 0.5574
Epoch 6/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.7370 - loss: 0.5421 - val_accuracy: 0.7290 - val_loss: 0.5535
Epoch 7/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.7311 - loss: 0.5522 - val_accuracy: 0.7283 - val_loss: 0.5564
Epoch 8/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.7339 - loss: 0.5453 - val_accuracy: 0.7296 - val_loss: 0.5576
Epoch 9/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7349 - loss: 0.5442 - val_accuracy: 0.7296 - val_loss: 0.5550
Epoch 10/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - accuracy: 0.7360 - loss: 0.5474 - val_accuracy: 0.7294 - val_loss: 0.5542
Epoch 11/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.7396 - loss: 0.5412 - val_accuracy: 0.7259 - val_loss: 0.5569
Epoch 12/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.7388 - loss: 0.5429 - val_accuracy: 0.7280 - val_loss: 0.5545
Epoch 13/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.7327 - loss: 0.5479 - val_accuracy: 0.7254 - val_loss: 0.5593
Epoch 14/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.7358 - loss: 0.5425 - val_accuracy: 0.7219 - val_loss: 0.5592
Epoch 15/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7362 - loss: 0.5433 - val_accuracy: 0.7235 - val_loss: 0.5559
Epoch 16/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7348 - loss: 0.5455 - val_accuracy: 0.7252 - val_loss: 0.5565
Epoch 17/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.7398 - loss: 0.5416 - val_accuracy: 0.7281 - val_loss: 0.5547
Epoch 18/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7364 - loss: 0.5411 - val_accuracy: 0.7264 - val_loss: 0.5582
Epoch 19/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.7408 - loss: 0.5384 - val_accuracy: 0.7270 - val_loss: 0.5556
Epoch 20/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.7365 - loss: 0.5447 - val_accuracy: 0.7280 - val_loss: 0.5575
Epoch 21/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7371 - loss: 0.5419 - val_accuracy: 0.7252 - val_loss: 0.5552
Epoch 22/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.7368 - loss: 0.5435 - val_accuracy: 0.7296 - val_loss: 0.5571
Epoch 23/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.7391 - loss: 0.5399 - val_accuracy: 0.7283 - val_loss: 0.5556
Epoch 24/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.7375 - loss: 0.5381 - val_accuracy: 0.7241 - val_loss: 0.5578
Epoch 25/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.7366 - loss: 0.5399 - val_accuracy: 0.7290 - val_loss: 0.5560
Epoch 26/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7371 - loss: 0.5416 - val_accuracy: 0.7277 - val_loss: 0.5574
Epoch 27/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.7363 - loss: 0.5404 - val_accuracy: 0.7270 - val_loss: 0.5563
Epoch 28/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7386 - loss: 0.5401 - val_accuracy: 0.7287 - val_loss: 0.5584
Epoch 29/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.7362 - loss: 0.5420 - val_accuracy: 0.7255 - val_loss: 0.5582
Epoch 30/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7381 - loss: 0.5372 - val_accuracy: 0.7265 - val_loss: 0.5576
Epoch 31/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.7359 - loss: 0.5409 - val_accuracy: 0.7283 - val_loss: 0.5578
Epoch 32/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.7362 - loss: 0.5408 - val_accuracy: 0.7293 - val_loss: 0.5568
Epoch 33/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.7405 - loss: 0.5388 - val_accuracy: 0.7265 - val_loss: 0.5570
Epoch 34/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - accuracy: 0.7374 - loss: 0.5423 - val_accuracy: 0.7268 - val_loss: 0.5575
Epoch 35/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7389 - loss: 0.5383 - val_accuracy: 0.7278 - val_loss: 0.5590
Epoch 36/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7398 - loss: 0.5394 - val_accuracy: 0.7264 - val_loss: 0.5614
Epoch 37/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - accuracy: 0.7382 - loss: 0.5389 - val_accuracy: 0.7283 - val_loss: 0.5610
Epoch 38/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.7406 - loss: 0.5333 - val_accuracy: 0.7271 - val_loss: 0.5608
Epoch 39/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7362 - loss: 0.5399 - val_accuracy: 0.7292 - val_loss: 0.5599
Epoch 40/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7363 - loss: 0.5429 - val_accuracy: 0.7283 - val_loss: 0.5593
Epoch 41/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7438 - loss: 0.5353 - val_accuracy: 0.7278 - val_loss: 0.5625
Epoch 42/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7361 - loss: 0.5422 - val_accuracy: 0.7270 - val_loss: 0.5611
Epoch 43/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.7395 - loss: 0.5377 - val_accuracy: 0.7280 - val_loss: 0.5607
Epoch 44/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7413 - loss: 0.5359 - val_accuracy: 0.7292 - val_loss: 0.5643
Epoch 45/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.7383 - loss: 0.5366 - val_accuracy: 0.7270 - val_loss: 0.5605
Epoch 46/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7398 - loss: 0.5377 - val_accuracy: 0.7278 - val_loss: 0.5587
Epoch 47/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7404 - loss: 0.5345 - val_accuracy: 0.7258 - val_loss: 0.5618
Epoch 48/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7380 - loss: 0.5368 - val_accuracy: 0.7267 - val_loss: 0.5586
Epoch 49/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.7417 - loss: 0.5331 - val_accuracy: 0.7294 - val_loss: 0.5606
Epoch 50/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7434 - loss: 0.5337 - val_accuracy: 0.7290 - val_loss: 0.5679
Epoch 51/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7383 - loss: 0.5389 - val_accuracy: 0.7283 - val_loss: 0.5594
Epoch 52/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.7422 - loss: 0.5341 - val_accuracy: 0.7278 - val_loss: 0.5633
Epoch 53/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.7389 - loss: 0.5376 - val_accuracy: 0.7280 - val_loss: 0.5657
Epoch 54/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7433 - loss: 0.5354 - val_accuracy: 0.7257 - val_loss: 0.5612
Epoch 55/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.7394 - loss: 0.5357 - val_accuracy: 0.7271 - val_loss: 0.5624
Epoch 56/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7359 - loss: 0.5417 - val_accuracy: 0.7277 - val_loss: 0.5673
Epoch 57/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7425 - loss: 0.5363 - val_accuracy: 0.7278 - val_loss: 0.5660
Epoch 58/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.7386 - loss: 0.5395 - val_accuracy: 0.7276 - val_loss: 0.5644
Epoch 59/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - accuracy: 0.7382 - loss: 0.5364 - val_accuracy: 0.7283 - val_loss: 0.5625
Epoch 60/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - accuracy: 0.7425 - loss: 0.5318 - val_accuracy: 0.7276 - val_loss: 0.5642
Epoch 61/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.7417 - loss: 0.5328 - val_accuracy: 0.7286 - val_loss: 0.5662
Epoch 62/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7401 - loss: 0.5345 - val_accuracy: 0.7276 - val_loss: 0.5644
Epoch 63/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7357 - loss: 0.5376 - val_accuracy: 0.7284 - val_loss: 0.5662
Epoch 64/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7393 - loss: 0.5315 - val_accuracy: 0.7278 - val_loss: 0.5646
Epoch 65/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.7407 - loss: 0.5324 - val_accuracy: 0.7281 - val_loss: 0.5641
Epoch 66/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7414 - loss: 0.5329 - val_accuracy: 0.7306 - val_loss: 0.5683
Epoch 67/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.7390 - loss: 0.5369 - val_accuracy: 0.7289 - val_loss: 0.5646
Epoch 68/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7394 - loss: 0.5345 - val_accuracy: 0.7290 - val_loss: 0.5687
Epoch 69/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7394 - loss: 0.5359 - val_accuracy: 0.7281 - val_loss: 0.5669
Epoch 70/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7384 - loss: 0.5355 - val_accuracy: 0.7289 - val_loss: 0.5680
Epoch 71/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.7359 - loss: 0.5362 - val_accuracy: 0.7273 - val_loss: 0.5686
Epoch 72/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7348 - loss: 0.5412 - val_accuracy: 0.7300 - val_loss: 0.5665
Epoch 73/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7408 - loss: 0.5291 - val_accuracy: 0.7292 - val_loss: 0.5684
Epoch 74/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.7442 - loss: 0.5303 - val_accuracy: 0.7261 - val_loss: 0.5706
Epoch 75/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7442 - loss: 0.5331 - val_accuracy: 0.7294 - val_loss: 0.5703
Epoch 76/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.7429 - loss: 0.5335 - val_accuracy: 0.7296 - val_loss: 0.5717
Epoch 77/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.7419 - loss: 0.5321 - val_accuracy: 0.7278 - val_loss: 0.5697
Epoch 78/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7371 - loss: 0.5372 - val_accuracy: 0.7255 - val_loss: 0.5668
Epoch 79/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7372 - loss: 0.5370 - val_accuracy: 0.7259 - val_loss: 0.5744
Epoch 80/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7399 - loss: 0.5352 - val_accuracy: 0.7290 - val_loss: 0.5685
Epoch 81/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7423 - loss: 0.5341 - val_accuracy: 0.7254 - val_loss: 0.5720
Epoch 82/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.7332 - loss: 0.5406 - val_accuracy: 0.7249 - val_loss: 0.5733
Epoch 83/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - accuracy: 0.7407 - loss: 0.5318 - val_accuracy: 0.7284 - val_loss: 0.5689
Epoch 84/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7421 - loss: 0.5339 - val_accuracy: 0.7280 - val_loss: 0.5714
Epoch 85/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7408 - loss: 0.5309 - val_accuracy: 0.7289 - val_loss: 0.5721
Epoch 86/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7377 - loss: 0.5386 - val_accuracy: 0.7286 - val_loss: 0.5704
Epoch 87/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.7439 - loss: 0.5296 - val_accuracy: 0.7236 - val_loss: 0.5757
Epoch 88/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.7387 - loss: 0.5357 - val_accuracy: 0.7293 - val_loss: 0.5808
Epoch 89/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.7364 - loss: 0.5374 - val_accuracy: 0.7289 - val_loss: 0.5770
Epoch 90/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.7437 - loss: 0.5338 - val_accuracy: 0.7264 - val_loss: 0.5760
Epoch 91/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7384 - loss: 0.5355 - val_accuracy: 0.7292 - val_loss: 0.5782
Epoch 92/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7431 - loss: 0.5305 - val_accuracy: 0.7273 - val_loss: 0.5747
Epoch 93/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7379 - loss: 0.5373 - val_accuracy: 0.7289 - val_loss: 0.5763
Epoch 94/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.7395 - loss: 0.5348 - val_accuracy: 0.7296 - val_loss: 0.5773
Epoch 95/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.7374 - loss: 0.5364 - val_accuracy: 0.7281 - val_loss: 0.5776
Epoch 96/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.7408 - loss: 0.5310 - val_accuracy: 0.7293 - val_loss: 0.5747
Epoch 97/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7371 - loss: 0.5354 - val_accuracy: 0.7293 - val_loss: 0.5727
Epoch 98/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.7427 - loss: 0.5301 - val_accuracy: 0.7294 - val_loss: 0.5765
Epoch 99/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7426 - loss: 0.5354 - val_accuracy: 0.7308 - val_loss: 0.5759
Epoch 100/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7430 - loss: 0.5316 - val_accuracy: 0.7293 - val_loss: 0.5837
215/215 - 0s - 2ms/step - accuracy: 0.7293 - loss: 0.5837

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

Optimized Loss: 0.5837362408638, Optimized Accuracy: 0.729300320148468